# Generated by Django 3.1.2 on 2020-11-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0005_auto_20201128_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
