# Generated by Django 3.1.2 on 2020-11-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0006_auto_20201129_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
