# Generated by Django 3.1.2 on 2020-12-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0007_auto_20201130_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
