# Generated by Django 3.1.2 on 2020-12-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='my-slug'),
            preserve_default=False,
        ),
    ]
