# Generated by Django 3.1.2 on 2020-12-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
