# Generated by Django 3.1.4 on 2021-01-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210128_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
